# Generated by Django 3.2.4 on 2021-06-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodhi', '0002_auto_20210622_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='desc1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='desc2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='desc3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='heading',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
