# Generated by Django 3.2.4 on 2021-06-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodhi', '0003_auto_20210622_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='gif',
            new_name='Img',
        ),
    ]
