# Generated by Django 3.2.4 on 2021-06-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodhi', '0004_rename_gif_services_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
